  export const appointments = [
    {
      appointment_id: "app_001",
      user: {
        user_id: "user_123",
        first_name: "Sarah",
        last_name: "Johnson",
        middle_initial: "M",
        phone_number: "+1234567890",
        sex: "female",
      },
      walk_in: null,
      branch: {
        branch_id: "branch_001",
        branch_name: "Downtown Beauty Center",
      },
      aesthetician: {
        aesthetician_id: "aes_456",
        first_name: "Maria",
        last_name: "Rodriguez",
        middle_initial: "L",
        experience: "pro",
      },
      service: {
        service_id: "serv_001",
        service_name: "Deep Cleansing Facial",
        final_price: 85.0,
        discounted_price: 75.0,
        category: "facial",
      },
      status: "completed",
      branch_rating: 5,
      service_rating: 5,
      aesthetician_rating: 5,
      service_comment:
        "Amazing facial! My skin feels so smooth and refreshed. Maria was very professional and explained each step of the process.",
      branch_comment:
        "Clean facility with a relaxing atmosphere. The staff was very welcoming.",
      aesthetician_comment:
        "Maria is incredibly skilled and made me feel comfortable throughout the entire session. Highly recommend!",
      down_payment_method: "credit_card",
      down_payment: 25.0,
      final_payment_method: "credit_card",
      to_pay: 0.0,
      payment_status: "paid",
      voucher_code: "NEWCLIENT10",
      discount_amount: 10.0,
      original_amount: 85.0,
      slot_number: 3,
      created_at: "2024-08-15T10:30:00Z",
      updated_at: "2024-08-15T12:45:00Z",
    },
    {
      appointment_id: "app_002",
      user: null,
      walk_in: {
        walk_in_id: "walk_001",
        first_name: "Jennifer",
        last_name: "Chen",
        middle_initial: "A",
        phone_number: "+1987654321",
        sex: "female",
      },
      branch: {
        branch_id: "branch_001",
        branch_name: "Downtown Beauty Center",
      },
      aesthetician: {
        aesthetician_id: "aes_456",
        first_name: "Maria",
        last_name: "Rodriguez",
        middle_initial: "L",
        experience: "pro",
      },
      service: {
        service_id: "serv_002",
        service_name: "Anti-Aging Treatment",
        final_price: 120.0,
        discounted_price: 120.0,
        category: "anti-aging",
      },
      status: "completed",
      branch_rating: 4,
      service_rating: 5,
      aesthetician_rating: 5,
      service_comment:
        "Excellent anti-aging treatment. I can already see improvements in my skin texture.",
      branch_comment: "Good location and parking availability.",
      aesthetician_comment:
        "Maria is a true professional. She customized the treatment based on my specific skin needs.",
      down_payment_method: "cash",
      down_payment: 50.0,
      final_payment_method: "cash",
      to_pay: 0.0,
      payment_status: "paid",
      voucher_code: null,
      discount_amount: 0.0,
      original_amount: 120.0,
      slot_number: 1,
      created_at: "2024-08-20T14:15:00Z",
      updated_at: "2024-08-20T16:30:00Z",
    },
    {
      appointment_id: "app_003",
      user: {
        user_id: "user_789",
        first_name: "Amanda",
        last_name: "Smith",
        middle_initial: "R",
        phone_number: "+1122334455",
        sex: "female",
      },
      walk_in: null,
      branch: {
        branch_id: "branch_001",
        branch_name: "Downtown Beauty Center",
      },
      aesthetician: {
        aesthetician_id: "aes_456",
        first_name: "Maria",
        last_name: "Rodriguez",
        middle_initial: "L",
        experience: "pro",
      },
      service: {
        service_id: "serv_003",
        service_name: "Hydrating Facial",
        final_price: 70.0,
        discounted_price: 60.0,
        category: "facial",
      },
      status: "completed",
      branch_rating: 5,
      service_rating: 4,
      aesthetician_rating: 5,
      service_comment:
        "Very relaxing and my skin feels so hydrated now. Great value for money.",
      branch_comment: "Love the ambiance and cleanliness of this place.",
      aesthetician_comment:
        "Maria has magic hands! She knew exactly what my skin needed. Will definitely be back.",
      down_payment_method: "debit_card",
      down_payment: 20.0,
      final_payment_method: "debit_card",
      to_pay: 0.0,
      payment_status: "paid",
      voucher_code: "LOYALTY15",
      discount_amount: 10.0,
      original_amount: 70.0,
      slot_number: 2,
      created_at: "2024-08-25T11:00:00Z",
      updated_at: "2024-08-25T13:15:00Z",
    },
    {
      appointment_id: "app_004",
      user: {
        user_id: "user_456",
        first_name: "Emily",
        last_name: "Davis",
        middle_initial: "K",
        phone_number: "+1555666777",
        sex: "female",
      },
      walk_in: null,
      branch: {
        branch_id: "branch_001",
        branch_name: "Downtown Beauty Center",
      },
      aesthetician: {
        aesthetician_id: "aes_456",
        first_name: "Maria",
        last_name: "Rodriguez",
        middle_initial: "L",
        experience: "pro",
      },
      service: {
        service_id: "serv_004",
        service_name: "Acne Treatment",
        final_price: 95.0,
        discounted_price: 85.0,
        category: "treatment",
      },
      status: "completed",
      branch_rating: 4,
      service_rating: 5,
      aesthetician_rating: 4,
      service_comment:
        "Great treatment for my acne-prone skin. Seeing improvements already!",
      branch_comment:
        "Professional environment, though could use more parking spaces.",
      aesthetician_comment:
        "Maria was knowledgeable about acne treatments and gave me great skincare advice.",
      down_payment_method: "credit_card",
      down_payment: 30.0,
      final_payment_method: "credit_card",
      to_pay: 0.0,
      payment_status: "paid",
      voucher_code: "STUDENT10",
      discount_amount: 10.0,
      original_amount: 95.0,
      slot_number: 4,
      created_at: "2024-08-28T09:30:00Z",
      updated_at: "2024-08-28T11:45:00Z",
    },
    {
      appointment_id: "app_005",
      user: null,
      walk_in: {
        walk_in_id: "walk_002",
        first_name: "Lisa",
        last_name: "Thompson",
        middle_initial: "J",
        phone_number: "+1999888777",
        sex: "female",
      },
      branch: {
        branch_id: "branch_001",
        branch_name: "Downtown Beauty Center",
      },
      aesthetician: {
        aesthetician_id: "aes_456",
        first_name: "Maria",
        last_name: "Rodriguez",
        middle_initial: "L",
        experience: "pro",
      },
      service: {
        service_id: "serv_005",
        service_name: "Brightening Facial",
        final_price: 80.0,
        discounted_price: 80.0,
        category: "facial",
      },
      status: "completed",
      branch_rating: 5,
      service_rating: 5,
      aesthetician_rating: 5,
      service_comment:
        "My skin looks noticeably brighter! The products used were top quality.",
      branch_comment:
        "Excellent service from start to finish. Very professional staff.",
      aesthetician_comment:
        "Maria is absolutely amazing! She made me feel so pampered and relaxed.",
      down_payment_method: "cash",
      down_payment: 40.0,
      final_payment_method: "cash",
      to_pay: 0.0,
      payment_status: "paid",
      voucher_code: null,
      discount_amount: 0.0,
      original_amount: 80.0,
      slot_number: 5,
      created_at: "2024-09-01T15:00:00Z",
      updated_at: "2024-09-01T17:15:00Z",
    },
    {
      appointment_id: "app_006",
      user: {
        user_id: "user_321",
        first_name: "Rachel",
        last_name: "Brown",
        middle_initial: "S",
        phone_number: "+1777888999",
        sex: "female",
      },
      walk_in: null,
      branch: {
        branch_id: "branch_001",
        branch_name: "Downtown Beauty Center",
      },
      aesthetician: {
        aesthetician_id: "aes_456",
        first_name: "Maria",
        last_name: "Rodriguez",
        middle_initial: "L",
        experience: "pro",
      },
      service: {
        service_id: "serv_001",
        service_name: "Deep Cleansing Facial",
        final_price: 85.0,
        discounted_price: 75.0,
        category: "facial",
      },
      status: "completed",
      branch_rating: 4,
      service_rating: 4,
      aesthetician_rating: 4,
      service_comment:
        "Good facial treatment, felt very clean afterwards. Recommend for monthly maintenance.",
      branch_comment:
        "Nice place, could improve the lighting in the waiting area.",
      aesthetician_comment:
        "Maria was professional and gentle. The facial was relaxing and effective.",
      down_payment_method: "digital_wallet",
      down_payment: 25.0,
      final_payment_method: "digital_wallet",
      to_pay: 0.0,
      payment_status: "paid",
      voucher_code: "REFER20",
      discount_amount: 10.0,
      original_amount: 85.0,
      slot_number: 1,
      created_at: "2024-09-03T13:45:00Z",
      updated_at: "2024-09-03T15:50:00Z",
    },
    {
      appointment_id: "app_007",
      user: {
        user_id: "user_654",
        first_name: "Michelle",
        last_name: "Wilson",
        middle_initial: "P",
        phone_number: "+1444555666",
        sex: "female",
      },
      walk_in: null,
      branch: {
        branch_id: "branch_001",
        branch_name: "Downtown Beauty Center",
      },
      aesthetician: {
        aesthetician_id: "aes_456",
        first_name: "Maria",
        last_name: "Rodriguez",
        middle_initial: "L",
        experience: "pro",
      },
      service: {
        service_id: "serv_006",
        service_name: "Microdermabrasion",
        final_price: 110.0,
        discounted_price: 100.0,
        category: "treatment",
      },
      status: "no_show",
      branch_rating: null,
      service_rating: null,
      aesthetician_rating: null,
      service_comment: null,
      branch_comment: null,
      aesthetician_comment: null,
      down_payment_method: "credit_card",
      down_payment: 35.0,
      final_payment_method: null,
      to_pay: 75.0,
      payment_status: "partial",
      voucher_code: "FIRST10",
      discount_amount: 10.0,
      original_amount: 110.0,
      slot_number: 2,
      created_at: "2024-09-05T10:00:00Z",
      updated_at: "2024-09-05T10:30:00Z",
    },
    {
      appointment_id: "app_008",
      user: {
        user_id: "user_987",
        first_name: "Nicole",
        last_name: "Martinez",
        middle_initial: "C",
        phone_number: "+1333444555",
        sex: "female",
      },
      walk_in: null,
      branch: {
        branch_id: "branch_001",
        branch_name: "Downtown Beauty Center",
      },
      aesthetician: {
        aesthetician_id: "aes_456",
        first_name: "Maria",
        last_name: "Rodriguez",
        middle_initial: "L",
        experience: "pro",
      },
      service: {
        service_id: "serv_007",
        service_name: "Chemical Peel",
        final_price: 135.0,
        discounted_price: 120.0,
        category: "treatment",
      },
      status: "upcoming",
      branch_rating: null,
      service_rating: null,
      aesthetician_rating: null,
      service_comment: null,
      branch_comment: null,
      aesthetician_comment: null,
      down_payment_method: "credit_card",
      down_payment: 45.0,
      final_payment_method: null,
      to_pay: 75.0,
      payment_status: "partial",
      voucher_code: "VIP15",
      discount_amount: 15.0,
      original_amount: 135.0,
      slot_number: 3,
      created_at: "2024-09-06T08:00:00Z",
      updated_at: "2024-09-06T08:00:00Z",
    },
  ];